name: build-test

on:
  pull_request:
    paths-ignore:
      - '**.md'    
  push:    
    branches:
      - main
      - master
      - releases/*
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [12.x, 14.x]
        mongodb-version: [4.0,4.2,4.4]
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: insert-your-replica-set-name

      - name: Run Audit
        run: npm audit

      - name: Run CI
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Code Coverage report
        run: npm run coverage

      - name: Check format with prettier/lint
        run: npm run prettier-format-check && npm run lint